In [1]:
import pandas as pd

In [2]:
file = '/home/stanislaw/Documents/work/Best_selling_games_in_history.csv'

In [3]:
dane = pd.read_csv(file)

In [4]:
dane.head(5)

,No.,Title,Developer,Publisher,Release date,Platform,Sales,Ref.
0,1,Tetris,Elektronorgtechnica,Spectrum HoloByte[b],"June 6, 1984",Multi-platform,170000000.0,[2]
1,2,Minecraft,Mojang,Mojang,"November 18, 2011",Multi-platform,122000000.0,[5]
2,3,Wii Sports,Nintendo EAD,Nintendo,"November 19, 2006",Wii,82810000.0,[6]
3,4,Grand Theft Auto V,Rockstar North,Rockstar Games,"September 17, 2013",Multi-platform,80000000.0,[8]
4,5,Super Mario Bros.,Nintendo R&D4,Nintendo,"September 13, 1985",NES,40240000.0,[9]

In [5]:
dane = dane.drop('Ref.',axis=1)
dane.head()

,No.,Title,Developer,Publisher,Release date,Platform,Sales
0,1,Tetris,Elektronorgtechnica,Spectrum HoloByte[b],"June 6, 1984",Multi-platform,170000000.0
1,2,Minecraft,Mojang,Mojang,"November 18, 2011",Multi-platform,122000000.0
2,3,Wii Sports,Nintendo EAD,Nintendo,"November 19, 2006",Wii,82810000.0
3,4,Grand Theft Auto V,Rockstar North,Rockstar Games,"September 17, 2013",Multi-platform,80000000.0
4,5,Super Mario Bros.,Nintendo R&D4,Nintendo,"September 13, 1985",NES,40240000.0

In [7]:
dane.groupby(by='Publisher').agg('sum').sort_values(by='Sales',ascending=False)

                             No.        Sales
Publisher
Nintendo                     414  561530000.0
Spectrum HoloByte[b]           1  170000000.0
Rockstar Games               119  165000000.0
Activision                   191  150000000.0
Mojang                         2  122000000.0
The Pokémon Company          196   81350000.0
Electronic Arts              127   47000000.0
Sega                          74   35000000.0
Bethesda Softworks            11   30000000.0
Blizzard Entertainment        12   30000000.0
Microsoft Studios             20   24000000.0
Psygnosis                     29   20000000.0
Re-Logic                      30   20000000.0
Sony Computer Entertainment   49   14890000.0

In [8]:
dane.groupby(by='Platform').agg('sum').sort_values(by='Sales',ascending=False)

                  No.        Sales
Platform
Multi-platform    550  774000000.0
Wii                91  254660000.0
Nintendo DS       211  145560000.0
NES                54   85820000.0
Game Boy           41   49520000.0
Nintendo 3DS      126   47390000.0
Xbox 360           20   24000000.0
Game Boy Color     23   23100000.0
Super NES          27   20610000.0
Game Boy Advance   37   16220000.0
Sega Mega Drive    46   15000000.0
PlayStation 2      49   14890000.0

In [9]:
dane.dtypes

No.               int64
Title            object
Developer        object
Publisher        object
Release date     object
Platform         object
Sales           float64
dtype: object

In [10]:
dane['Release date'] = pd.to_datetime(dane['Release date'])

In [11]:
dane['year'] = dane['Release date'].map(lambda x: x.strftime('%Y'))

In [12]:
dane

,No.,Title,Developer,Publisher,Release date,Platform,Sales,year
0,1,Tetris,Elektronorgtechnica,Spectrum HoloByte[b],1984-06-06,Multi-platform,170000000.0,1984
1,2,Minecraft,Mojang,Mojang,2011-11-18,Multi-platform,122000000.0,2011
2,3,Wii Sports,Nintendo EAD,Nintendo,2006-11-19,Wii,82810000.0,2006
3,4,Grand Theft Auto V,Rockstar North,Rockstar Games,2013-09-17,Multi-platform,80000000.0,2013
4,5,Super Mario Bros.,Nintendo R&D4,Nintendo,1985-09-13,NES,40240000.0,1985
5,6,Mario Kart Wii,Nintendo EAD,Nintendo,2008-04-10,Wii,36950000.0,2008
6,7,Wii Sports Resort,Nintendo EAD,Nintendo,2009-06-25,Wii,33040000.0,2009
7,8,Pokémon Red Green and Blue,Game Freak,Nintendo,1996-02-27,Game Boy,31380000.0,1996
8,9,New Super Mario Bros.,Nintendo EAD,Nintendo,2006-05-15,Nintendo DS,30800000.0,2006
9,10,New Super Mario Bros. Wii,Nintendo EAD,Nintendo,2009-11-11,Wii,30050000.0,2009
10,11,The Elder Scrolls V: Skyrim,Bethesda Game Studios,Bethesda Softworks,2011-11-11,Multi-platform,30000000.0,2011
11,12,Diablo III,Blizzard Entertainment,Blizzard Entertainment,2012-05-15,Multi-platform,30000000.0,2012
12,13,Duck Hunt,Nintendo R&D1,Nintendo,1984-04-21,NES,28300000.0,1984
13,14,Wii Play,Nintendo EAD,Nintendo,2006-12-02,Wii,28020000.0,2006
14,15,Grand Theft Auto: San Andreas,Rockstar North,Rockstar Games,2004-10-26,Multi-platform,27500000.0,2004
15,16,Call of Duty: Modern Warfare 3,Infinity Ward\r\nSledgehammer Games,Activision,2011-11-08,Multi-platform,26500000.0,2011
16,17,Call of Duty: Black Ops,Treyarch,Activision,2010-11-09,Multi-platform,26200000.0,2010
17,18,Grand Theft Auto IV,Rockstar North,Rockstar Games,2008-04-29,Multi-platform,25000000.0,2008
18,19,Call of Duty: Black Ops II,Treyarch,Activision,2012-11-12,Multi-platform,24200000.0,2012
19,20,Kinect Adventures!,Good Science Studio,Microsoft Studios,2010-11-04,Xbox 360,24000000.0,2010
20,21,Nintendogs,Nintendo EAD,Nintendo,2005-04-21,Nintendo DS,23960000.0,2005
21,22,Mario Kart DS,Nintendo EAD,Nintendo,2005-11-14,Nintendo DS,23600000.0,2005
22,23,Pokémon Gold and Silver,Game Freak,Nintendo,1999-11-21,Game Boy Color,23100000.0,1999
23,24,Call of Duty: Modern Warfare 2,Infinity Ward,Activision,2009-11-10,Multi-platform,22700000.0,2009
24,25,Wii Fit,Nintendo EAD,Nintendo,2007-12-01,Wii,22670000.0,2007
25,26,Wii Fit Plus,Nintendo EAD,Nintendo,2009-10-01,Wii,21120000.0,2009
26,27,Super Mario World,Nintendo EAD,Nintendo,1990-11-21,Super NES,20610000.0,1990
27,28,Frogger,Konami,Sega,1981-06-05,Multi-platform,20000000.0,1981
28,29,Lemmings,DMA Design,Psygnosis,1991-02-14,Multi-platform,20000000.0,1991
29,30,Terraria,Re-Logic,Re-Logic,2011-05-16,Multi-platform,20000000.0,2011
30,31,Brain Age,Nintendo SPD,Nintendo,2005-05-19,Nintendo DS,19010000.0,2005
31,32,Call of Duty: Ghosts,Infinity Ward,Activision,2013-11-05,Multi-platform,19000000.0,2013
32,33,Super Mario Land,Nintendo R&D1,Nintendo,1989-04-21,Game Boy,18140000.0,1989
33,34,Pokémon Diamond and Pearl,Game Freak,The Pokémon Company,2006-09-28,Nintendo DS,17670000.0,2006
34,35,Grand Theft Auto: Vice City,Rockstar North,Rockstar Games,2002-10-27,Multi-platform,17500000.0,2002
35,36,Super Mario Bros. 3,Nintendo R&D4,Nintendo,1988-10-23,NES,17280000.0,1988
36,37,Pokémon Ruby and Sapphire,Game Freak,The Pokémon Company,2002-11-21,Game Boy Advance,16220000.0,2002
37,38,Pokémon X and Y,Game Freak,The Pokémon Company,2013-10-12,Nintendo 3DS,16150000.0,2013
38,39,The Sims,Maxis,Electronic Arts,2000-01-31,Multi-platform,16000000.0,2000
39,40,Need for Speed: Most Wanted,EA Black Box,Electronic Arts,2005-11-11,Multi-platform,16000000.0,2005
40,41,Call of Duty 4: Modern Warfare,Infinity Ward,Activision,2007-11-05,Multi-platform,15700000.0,2007
41,42,Call of Duty: World at War,Treyarch,Activision,2008-11-11,Multi-platform,15700000.0,2008
42,43,Pokémon Sun and Moon,Game Freak,The Pokémon Company,2016-11-18,Nintendo 3DS,15670000.0,2016
43,44,Pokémon Black and White,Game Freak,The Pokémon Company,2010-09-18,Nintendo DS,15640000.0,2010
44,45,Mario Kart 7,Nintendo EAD,Nintendo,2011-12-01,Nintendo 3DS,15570000.0,2011
45,46,Sonic the Hedgehog,Sonic Team,Sega,1991-06-23,Sega Mega Drive,15000000.0,1991
46,47,Red Dead Redemption,Rockstar San Diego,Rockstar Games,2010-05-18,Multi-platform,15000000.0,2010
47,48,Battlefield 3,EA DICE,Electronic Arts,2011-10-25,Multi-platform,15000000.0,2011
48,49,Gran Turismo 3: A-Spec,Polyphony Digital,Sony Computer Entertainment,2001-04-28,PlayStation 2,14890000.0,2001
49,50,Brain Age 2,Nintendo SPD,Nintendo,2005-12-29,Nintendo DS,14880000.0,2005

In [13]:
dane.groupby(by='year').agg('sum').sort_values(by='Sales',ascending=False)

      No.        Sales
year
2011  152  229070000.0
1984   14  198300000.0
2006   60  159300000.0
2013   74  115150000.0
2009   67  106910000.0
2005  164   97450000.0
2010  128   80840000.0
2008   66   77650000.0
2012   31   54200000.0
1985    5   40240000.0
2007   66   38370000.0
1991   75   35000000.0
2002   72   33720000.0
1996    8   31380000.0
2004   15   27500000.0
1999   23   23100000.0
1990   27   20610000.0
1981   28   20000000.0
1989   33   18140000.0
1988   36   17280000.0
2000   39   16000000.0
2016   43   15670000.0
2001   49   14890000.0

In [14]:
dane.groupby(by='year').agg('count')

      No.  Title  Developer  Publisher  Release date  Platform  Sales
year
1981    1      1          1          1             1         1      1
1984    2      2          2          2             2         2      2
1985    1      1          1          1             1         1      1
1988    1      1          1          1             1         1      1
1989    1      1          1          1             1         1      1
1990    1      1          1          1             1         1      1
1991    2      2          2          2             2         2      2
1996    1      1          1          1             1         1      1
1999    1      1          1          1             1         1      1
2000    1      1          1          1             1         1      1
2001    1      1          1          1             1         1      1
2002    2      2          2          2             2         2      2
2004    1      1          1          1             1         1      1
2005    5      5          5          5             5         5      5
2006    4      4          4          4             4         4      4
2007    2      2          2          2             2         2      2
2008    3      3          3          3             3         3      3
2009    4      4          4          4             4         4      4
2010    4      4          4          4             4         4      4
2011    6      6          6          6             6         6      6
2012    2      2          2          2             2         2      2
2013    3      3          3          3             3         3      3
2016    1      1          1          1             1         1      1

In [15]:
dane.sort_values(by='year')

,No.,Title,Developer,Publisher,Release date,Platform,Sales,year
27,28,Frogger,Konami,Sega,1981-06-05,Multi-platform,20000000.0,1981
0,1,Tetris,Elektronorgtechnica,Spectrum HoloByte[b],1984-06-06,Multi-platform,170000000.0,1984
12,13,Duck Hunt,Nintendo R&D1,Nintendo,1984-04-21,NES,28300000.0,1984
4,5,Super Mario Bros.,Nintendo R&D4,Nintendo,1985-09-13,NES,40240000.0,1985
35,36,Super Mario Bros. 3,Nintendo R&D4,Nintendo,1988-10-23,NES,17280000.0,1988
32,33,Super Mario Land,Nintendo R&D1,Nintendo,1989-04-21,Game Boy,18140000.0,1989
26,27,Super Mario World,Nintendo EAD,Nintendo,1990-11-21,Super NES,20610000.0,1990
28,29,Lemmings,DMA Design,Psygnosis,1991-02-14,Multi-platform,20000000.0,1991
45,46,Sonic the Hedgehog,Sonic Team,Sega,1991-06-23,Sega Mega Drive,15000000.0,1991
7,8,Pokémon Red Green and Blue,Game Freak,Nintendo,1996-02-27,Game Boy,31380000.0,1996
22,23,Pokémon Gold and Silver,Game Freak,Nintendo,1999-11-21,Game Boy Color,23100000.0,1999
38,39,The Sims,Maxis,Electronic Arts,2000-01-31,Multi-platform,16000000.0,2000
48,49,Gran Turismo 3: A-Spec,Polyphony Digital,Sony Computer Entertainment,2001-04-28,PlayStation 2,14890000.0,2001
34,35,Grand Theft Auto: Vice City,Rockstar North,Rockstar Games,2002-10-27,Multi-platform,17500000.0,2002
36,37,Pokémon Ruby and Sapphire,Game Freak,The Pokémon Company,2002-11-21,Game Boy Advance,16220000.0,2002
14,15,Grand Theft Auto: San Andreas,Rockstar North,Rockstar Games,2004-10-26,Multi-platform,27500000.0,2004
21,22,Mario Kart DS,Nintendo EAD,Nintendo,2005-11-14,Nintendo DS,23600000.0,2005
30,31,Brain Age,Nintendo SPD,Nintendo,2005-05-19,Nintendo DS,19010000.0,2005
39,40,Need for Speed: Most Wanted,EA Black Box,Electronic Arts,2005-11-11,Multi-platform,16000000.0,2005
20,21,Nintendogs,Nintendo EAD,Nintendo,2005-04-21,Nintendo DS,23960000.0,2005
49,50,Brain Age 2,Nintendo SPD,Nintendo,2005-12-29,Nintendo DS,14880000.0,2005
2,3,Wii Sports,Nintendo EAD,Nintendo,2006-11-19,Wii,82810000.0,2006
13,14,Wii Play,Nintendo EAD,Nintendo,2006-12-02,Wii,28020000.0,2006
8,9,New Super Mario Bros.,Nintendo EAD,Nintendo,2006-05-15,Nintendo DS,30800000.0,2006
33,34,Pokémon Diamond and Pearl,Game Freak,The Pokémon Company,2006-09-28,Nintendo DS,17670000.0,2006
24,25,Wii Fit,Nintendo EAD,Nintendo,2007-12-01,Wii,22670000.0,2007
40,41,Call of Duty 4: Modern Warfare,Infinity Ward,Activision,2007-11-05,Multi-platform,15700000.0,2007
17,18,Grand Theft Auto IV,Rockstar North,Rockstar Games,2008-04-29,Multi-platform,25000000.0,2008
41,42,Call of Duty: World at War,Treyarch,Activision,2008-11-11,Multi-platform,15700000.0,2008
5,6,Mario Kart Wii,Nintendo EAD,Nintendo,2008-04-10,Wii,36950000.0,2008
9,10,New Super Mario Bros. Wii,Nintendo EAD,Nintendo,2009-11-11,Wii,30050000.0,2009
6,7,Wii Sports Resort,Nintendo EAD,Nintendo,2009-06-25,Wii,33040000.0,2009
25,26,Wii Fit Plus,Nintendo EAD,Nintendo,2009-10-01,Wii,21120000.0,2009
23,24,Call of Duty: Modern Warfare 2,Infinity Ward,Activision,2009-11-10,Multi-platform,22700000.0,2009
16,17,Call of Duty: Black Ops,Treyarch,Activision,2010-11-09,Multi-platform,26200000.0,2010
46,47,Red Dead Redemption,Rockstar San Diego,Rockstar Games,2010-05-18,Multi-platform,15000000.0,2010
19,20,Kinect Adventures!,Good Science Studio,Microsoft Studios,2010-11-04,Xbox 360,24000000.0,2010
43,44,Pokémon Black and White,Game Freak,The Pokémon Company,2010-09-18,Nintendo DS,15640000.0,2010
47,48,Battlefield 3,EA DICE,Electronic Arts,2011-10-25,Multi-platform,15000000.0,2011
1,2,Minecraft,Mojang,Mojang,2011-11-18,Multi-platform,122000000.0,2011
44,45,Mario Kart 7,Nintendo EAD,Nintendo,2011-12-01,Nintendo 3DS,15570000.0,2011
10,11,The Elder Scrolls V: Skyrim,Bethesda Game Studios,Bethesda Softworks,2011-11-11,Multi-platform,30000000.0,2011
15,16,Call of Duty: Modern Warfare 3,Infinity Ward\r\nSledgehammer Games,Activision,2011-11-08,Multi-platform,26500000.0,2011
29,30,Terraria,Re-Logic,Re-Logic,2011-05-16,Multi-platform,20000000.0,2011
11,12,Diablo III,Blizzard Entertainment,Blizzard Entertainment,2012-05-15,Multi-platform,30000000.0,2012
18,19,Call of Duty: Black Ops II,Treyarch,Activision,2012-11-12,Multi-platform,24200000.0,2012
3,4,Grand Theft Auto V,Rockstar North,Rockstar Games,2013-09-17,Multi-platform,80000000.0,2013
37,38,Pokémon X and Y,Game Freak,The Pokémon Company,2013-10-12,Nintendo 3DS,16150000.0,2013
31,32,Call of Duty: Ghosts,Infinity Ward,Activision,2013-11-05,Multi-platform,19000000.0,2013
42,43,Pokémon Sun and Moon,Game Freak,The Pokémon Company,2016-11-18,Nintendo 3DS,15670000.0,2016